### ISSUE TITLE
No install.sh script

### ISSUE THREAD

**Issue by cawabunga** [savonarola/homedir2#2]
Hello, I can't install configs using script from README. Because of absence of `install.sh`, which was removed in https://github.com/savonarola/homedir/commit/ac0515af23094fce60015aa53e1215ba07cf70de

```
bash <(curl -s https://raw.githubusercontent.com/savonarola/homedir/master/install.sh)
```

**Comment by savonarola** [comment]
Hello!

`.sh`-scripts were needed many years ago to bootstrap on servers not having `git` and/or internet access.

Luckily, for the last several years I haven't met any such servers.

I updated the readme: added the only way I now use to install. Also dropped some legacy scripts.
